### PR TITLE
#6 Check Through for Grammar and Spelling 

### PR DESCRIPTION
**Pull request by BigSteveLittle**
This is a site-wide check of grammar and spelling. A few other issues have been raised from this process.

* Upgrade the Confirmation page for the Contact Form #17
* Correct the Left Section Left Margin on the Editing and Screenwriting Pages #18
* Create a Portfolio Landing Page #19

@EngelbertHumperdinck can you review and approve, please?

Thanks
@BigSteveLittle

### CODE REVIEW

**Review by EngelbertHumperdinck — CHANGES_REQUESTED** [review]
Hi @BigSteveLittle,

A worthwhile update! I found 2 corrections required: 
1.  [public_html/steve-little-cms-development.html](https://github.com/RedAndBlackZone/redandblackzone/pull/20/files#diff-91948f6c41e3ea862bd1105ec6eb10471d221782d462eb3e1e7a2ff1dacfbaf8)  - As this is a Heading the word ‘found’ should be capitalised [Found] to be consistent.
2.  [public_html/steve-little-story.html](https://github.com/RedAndBlackZone/redandblackzone/pull/20/files#diff-0e472b846117e6684696eb1f702ee497436741eeba5c0f23442942e74c6fb06a)  - The word ‘the’ is missing from ‘featuring best action shots’ in the last sentence of the left-hand section.

Cheers
@EngelbertHumperdinck

**Comment by BigSteveLittle** [comment]
> 

Thanks @EngelbertHumperdinck, I'll make these changes now and re-submit. @BigSteveLittle

**Comment by BigSteveLittle** [comment]
> > 
> 
> Thanks @EngelbertHumperdinck, I'll make these changes now and re-submit. @BigSteveLittle

Changes are made @EngelbertHumperdinck. Can you approve now, please? Thanks, @BigSteveLittle.

**Review by EngelbertHumperdinck — APPROVED** [review]
Looks good @BigSteveLittle You can merge and release. Thanks @EngelbertHumperdinck

**Pull request merged**
